version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api-builder
    volumes:
      - .:/go/src/github.com/yach36/clean-arch-prac
    stdin_open: true
    tty: true
    environment:
      - GOPATH=/go
      - TZ=Asia/Tokyo
    ports:
      - 8080:8080
    depends_on:
      - db
  grpc:
    container_name: grpc
    build:
      context: .
      dockerfile: ./Dockerfile
      target: grpc-builder
    volumes:
      - .:/go/src/github.com/yach36/clean-arch-prac
    stdin_open: true
    tty: true
    environment:
      - GOPATH=/go
      - TZ=Asia/Tokyo
    ports:
      - 50051:50051
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    volumes:
      - clean-arch-prac-volume:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
networks:
  default:
    name: clean-arch-prac-network
volumes:
  clean-arch-prac-volume:
    name: clean-arch-prac-volume
